steps:
  - name: node:14.17.6
    entrypoint: sh
    args:
      - -c
      - |
        npm install
        npm run build
  - name: 'gcr.io/cloud-builders/firebase'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        firebase deploy --only hosting
