steps:
  - name: node:14.17.6
    entrypoint: sh
    args:
      - -c
      - |
        npm install
        npm run build
        npm install -g firebase-tools
  - name: bash
    script: |
        firebase deploy --token=$FIREBASE_TOKEN --only hosting
