steps:
  # Install dependencies and build the ReactJS code.
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
  # Deploy to Firebase Hosting.
  - name: 'gcr.io/910471305192/firebase'
    args: ['deploy', '--project=dev-frontend-reactjs', '--only', 'hosting']
