steps:
  # Install dependencies and build the ReactJS code.
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
  # Deploy to Firebase Hosting.
  - name: gcr.io/project-id/firebase
    args: ['deploy', '--project=firebase-project-id', '--only=hosting']
