steps:
  - name: node:14.17.6
    entrypoint: sh
    args:
      - -c
      - |
        npm install
        npm run build
  - name: 'firebase'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install -g firebase-tools
        firebase deploy --only hosting
